using System;
using System.Collections.Generic;
using System.Data;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Xml.Linq;

public class CUSTOMERUTILITYPAYMENTManager
{
	public CUSTOMERUTILITYPAYMENTManager()
	{
	}

    public static List<CUSTOMERUTILITYPAYMENT> GetAllCUSTOMERUTILITYPAYMENTs()
    {
        List<CUSTOMERUTILITYPAYMENT> cUSTOMERUTILITYPAYMENTs = new List<CUSTOMERUTILITYPAYMENT>();
        SqlCUSTOMERUTILITYPAYMENTProvider sqlCUSTOMERUTILITYPAYMENTProvider = new SqlCUSTOMERUTILITYPAYMENTProvider();
        cUSTOMERUTILITYPAYMENTs = sqlCUSTOMERUTILITYPAYMENTProvider.GetAllCUSTOMERUTILITYPAYMENTs();
        return cUSTOMERUTILITYPAYMENTs;
    }


    public static CUSTOMERUTILITYPAYMENT GetCUSTOMERUTILITYPAYMENTByID(int id)
    {
        CUSTOMERUTILITYPAYMENT cUSTOMERUTILITYPAYMENT = new CUSTOMERUTILITYPAYMENT();
        SqlCUSTOMERUTILITYPAYMENTProvider sqlCUSTOMERUTILITYPAYMENTProvider = new SqlCUSTOMERUTILITYPAYMENTProvider();
        cUSTOMERUTILITYPAYMENT = sqlCUSTOMERUTILITYPAYMENTProvider.GetCUSTOMERUTILITYPAYMENTByID(id);
        return cUSTOMERUTILITYPAYMENT;
    }


    public static int InsertCUSTOMERUTILITYPAYMENT(CUSTOMERUTILITYPAYMENT cUSTOMERUTILITYPAYMENT)
    {
        SqlCUSTOMERUTILITYPAYMENTProvider sqlCUSTOMERUTILITYPAYMENTProvider = new SqlCUSTOMERUTILITYPAYMENTProvider();
        return sqlCUSTOMERUTILITYPAYMENTProvider.InsertCUSTOMERUTILITYPAYMENT(cUSTOMERUTILITYPAYMENT);
    }


    public static bool UpdateCUSTOMERUTILITYPAYMENT(CUSTOMERUTILITYPAYMENT cUSTOMERUTILITYPAYMENT)
    {
        SqlCUSTOMERUTILITYPAYMENTProvider sqlCUSTOMERUTILITYPAYMENTProvider = new SqlCUSTOMERUTILITYPAYMENTProvider();
        return sqlCUSTOMERUTILITYPAYMENTProvider.UpdateCUSTOMERUTILITYPAYMENT(cUSTOMERUTILITYPAYMENT);
    }

    public static bool DeleteCUSTOMERUTILITYPAYMENT(int cUSTOMERUTILITYPAYMENTID)
    {
        SqlCUSTOMERUTILITYPAYMENTProvider sqlCUSTOMERUTILITYPAYMENTProvider = new SqlCUSTOMERUTILITYPAYMENTProvider();
        return sqlCUSTOMERUTILITYPAYMENTProvider.DeleteCUSTOMERUTILITYPAYMENT(cUSTOMERUTILITYPAYMENTID);
    }
}
